version: '2'
services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80

  db:
    restart: always
    image: postgres:9.4

  redis:
    restart: always
    image: redis:4.0.9

  server:
    restart: always
    build: ./server
    command: gunicorn config.wsgi -w 4 -b 0.0.0.0:8000 -t 60
    depends_on:
      - redis
      - db
      - calculate-proxy-server
    environment:
      DEBUG: 'False'
      DATABASE_URL: postgres://postgres@db/postgres
      REDIS_URL: 'redis://redis/0'

  calculate-proxy-server:
    restart: always
    build: ./server
    command: gunicorn config.wsgi -w 1 -b 0.0.0.0:8001 -t 60
    depends_on:
      - redis
      - db
    environment:
      DEBUG: 'False'
      DATABASE_URL: postgres://postgres@db/postgres
      REDIS_URL: 'redis://redis/0'
