version: '2'
services:
  db:
    image: postgres:9.4

  redis:
    image: redis:4.0.9

  server:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn config.wsgi -w 4 -b 0.0.0.0:8000 -t 60
    ports:
      - 8000:8000
    volumes:
    - ./server:/app/user
    depends_on:
      - redis
      - db
      - calculate-proxy-server
    environment:
      DEBUG: 'True'
      DATABASE_URL: postgres://postgres@db/postgres
      REDIS_URL: 'redis://redis/0'

  calculate-proxy-server:
    build: ./server
    command: python manage.py runserver --nothreading 0.0.0.0:8001
#    command: gunicorn config.wsgi -w 1 -b 0.0.0.0:8001 -t 60
    ports:
      - 8001:8001
    volumes:
    - ./server:/app/user
    depends_on:
      - redi
      - server
      - db
    environment:
      DEBUG: 'True'
      DATABASE_URL: postgres://postgres@db/postgres
      REDIS_URL: 'redis://redis/0'
